### PR TITLE
Save the model's cmetaId and base XML URI with a simulation result set.

### PR DESCRIPTION
**Pull request by dbrnz**

### CODE REVIEW

**Comment by agarny** [comment]
This looks good to me. Just waiting for the CI build result before accepting.

**Comment by agarny** [comment]
Also, a PR probably ought to be generated only when everything it relies on has been accepted. Right now, this PR is about to fail...

**Comment by agarny** [comment]
FWIW, PR #624 has now been merged and has been 'cleaned', so you should be able to correct your PR.

**Comment by dbrnz** [comment]
This should now be ready to go, thanks.

**Comment by agarny** [comment]
Although I have now merged your PR, I was wondering whether the model ID and model URI couldn't be provided in the constructor through the runtime. In other words, rather than having:

```
mDataStore = new CoreDataStore::CoreDataStore(simulationSize);
mDataStore->setModelId(mRuntime->cellmlFile()->cmetaId());
mDataStore->setModelUri(mRuntime->cellmlFile()->xmlBase());
```

we could have:

```
mDataStore = new CoreDataStore::CoreDataStore(mRuntime, simulationSize);
```

Then, it would be the ```CoreDataStore``` constructor that would initialise its ```mModelId``` and ```mModelUri``` class members using ```mRuntime```.

This also means that ```CoreDataStore::setModelId()``` and ```CoreDataStore::setModelUri()``` wouldn't be needed, which I think would make sense. That is unless I missed something and that both the a model ID and model URI can be changed afterwards?

Let me know (I am happy to implement what I have just described).

**Comment by dbrnz** [comment]
What you have suggested makes sense, especially as the model ID and URI is a constant of a data store. It would be great if you could implement this, but there's no urgency from my POV. Thanks!

**Comment by agarny** [comment]
I have just noticed that ```CoreDataStore``` doesn't know (and shouldn't have to know) about the runtime (since the one we are currently using is specific to CellML while we might, at some point, have one for SBML, etc.). Still, I don't think the id and URI should be modifiable. Anyway, see what I have done [here](https://github.com/opencor/opencor/commit/4aeda249f1456960930feb507d06d5e2da71560d). You will see that I refere to ```mId``` and ```mUri``` and not ```modelId``` and ```modelUri``` since we might want a data store for something that is not a model (e.g. some experimental data). Otherwise, why the need for both ```mId``` and ```mUri```? Wouldn't ```mUri``` be sufficient? Then again, for a local CellML file, ```mId``` would be empty and ```mUri``` refer to a local file, so not necessarily something unique in the long run...

**Pull request merged**
