### PR TITLE
"All Files" option should be last in list of file filters.

### PR DESCRIPTION
**Pull request by dbrnz**

### CODE REVIEW

**Comment by agarny** [comment]
Why do you think ```All Files``` should be last? I have just 'checked' with Qt Creator on OS X and ```All Files``` is first. Same with Notepad++ on Windows and Firefox on Linux. So, there seems to be some kind of consensus between different applications and OSes that ```All Files``` should be first. In fact, if it wasn't to be first, then it means that another filter would have to be and it might not be the 'best' one.

So, I am inclined to refuse your pull request, sorry...

**Comment by dbrnz** [comment]
Hmm, under OS/X, and with `All Files` first in the list of filters, the file type selection box at the bottom of the "Save File" dialogue has "All Files" selected. I'm used to having the default file type (in this case either `csv` or `h5`) as the default selection and the extension then appended to whatever file name was entered.

Alternatively is their an option to `Core::getSaveFileName()` that will result in the supplied filter being used as default?

**Comment by agarny** [comment]
```Core::getSaveFileName()``` doesn't currently allow that, not least because several filters could be passed to that function. Still, underneath, that function calls ```QFileDialog::getSaveFileName()```, which allows for a filter to be selected (see [here](http://doc.qt.io/qt-5/qfiledialog.html#getSaveFileName)). So, I guess we could/should allow it too in ```Core::getSaveFileName()```, as well as in ```Core::getOpenFileName()``` and ```Core::getOpenFileNames()```. Ok, I have created an issue for it (see issue #626). Will look into it tomorrow.

**Comment by agarny** [comment]
Closing as "won't do". However, issue #626 should help with this.

**Pull request closed without merging**
