### PR TITLE
PMR Workspaces

### PR DESCRIPTION
**Pull request by dbrnz**
Here is my PMR branch which is current with `master` as of two days ago. The main thing to watch in merging is a rename of `./support/PMRSupport/src/pmrwebservice.*` to `./support/PMRSupport/src/pmrrepository.*`; everything else should be fine.

### CODE REVIEW

**Comment by agarny** [comment]
Thanks for this @dbrnz. Otherwise, why was `./support/PMRSupport/src/pmrwebservice.*` renamed to `./support/PMRSupport/src/pmrrepository.*`? It's kind of redundant considering that PMR stands for Physiome Model Repository...

**Comment by agarny** [comment]
Hmm, the Travis CI builds are failing (see [here](https://travis-ci.org/opencor/opencor/builds/166820117)).

**Comment by agarny** [comment]
I get the feeling from the build logs that there are some Git submodules involved, something I didn't want... :(

**Comment by dbrnz** [comment]
Hopefully I've resolved the Travis issue with the submodule -- my bad in using a `git` URL scheme instead of `https` to reference the repository.

**Comment by agarny** [comment]
I am currently working towards upgrading to Qt 5.6.2 (it has been released this morning), so it's bound to break. I am hoping to be done with the Qt 5.6.2 upgrade sometime tomorrow (with the release of OpenCOR 0.5).

**Comment by dbrnz** [comment]
@agarny, I accept your point regarding `pmrrepository` versus `pmrwebservice` so am now resolving this.

**Comment by agarny** [comment]
Thanks for all of this @dbrnz. I am going to merge it and will start looking at it ASAP.

**Comment by agarny** [comment]
Hmm... bad start, I have just merged your PR and then pulled everything locally. Now, trying to build OpenCOR, I am getting the following:

```
Building a release version of OpenCOR for OS X 10.8 and later using Qt 5.6.2...
-- Configuring done
CMake Error at cmake/common.cmake:526 (ADD_LIBRARY):
  Cannot find source file:

    o2/src/o0baseauth.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  src/plugins/thirdParty/OAuth/CMakeLists.txt:7 (ADD_PLUGIN)


CMake Error: CMake can not determine linker language for target: OAuthPlugin
-- Generating done
-- Build files have been written to: /Users/Alan/OpenCOR/build
```

I take it that I need to do something on the Git side of things due to your use of Git modules? If so, that kind of confirms why I am not too keen on that approach. Anyway, will look into it.

**Comment by dbrnz** [comment]
You need `git submodule update --init --recursive` to pull in and update sub modules.

**Comment by agarny** [comment]
Yes, I remembered something like that indeed. Still, I am not to keen on having to rely on Git submodules. I mean some people might not update to the latest version or something. So, right now, I am inclined to actually making the contents of your `win_export` part of the OpenCOR codebase (in the same way that I did that for `LLVM`, which I also had to modify to allow for symbols to be exported on Windows).

**Pull request merged**
