### PR TITLE
Mapping: need display the Zinc mesh during a simulation (#2404)

### PR DESCRIPTION
**Pull request by LafCorentin**
Bring the view of the 3D model during the simulation

Addresses issue #2404.

### CODE REVIEW

**Comment by abi-git-user** [comment]
Can one of the admins verify this patch?

**Comment by abi-git-user** [comment]
Can one of the admins verify this patch?

**Comment by agarny** [comment]
@LafCorentin, could you please tell me whether this is ready to be merged?

**Comment by LafCorentin** [comment]
yes it is ready to merge

Le ven. 30 oct. 2020 à 10:04, Alan Garny <notifications@github.com> a
écrit :

**Comment by agarny** [comment]
Ok, thanks @LafCorentin. I am going to do that and will then proceed with the cleaning up, etc. that we discussed before.

**Pull request merged**
