### PR TITLE
Add a simulation support plugin (to separate out running of a simulation from its widget) (#1266)

### PR DESCRIPTION
**Pull request by agarny**

### CODE REVIEW

**Comment by alan-wu** [comment]
Hi Alan, all plugins are no longer working except for the solver one after I pull the latest changes in, am I doing something wrong?

**Comment by dbrnz** [comment]
@alan-wu, OpenCOR with the latest changes builds and runs just fine for me. Did you run `./clean` before building? Does `ldd` (linux) or `otool -L` (macos) show anything unusual (e.g. non-relative paths) when run on plugin shared libraries??

**Comment by alan-wu** [comment]
@dbrnz I tried build clean then build uising qt creator and got the same problem, by the way, I am building it on windows.

**Comment by alan-wu** [comment]
@dbrnz I will blow everything away and run build again, problem could be caused by the dlls being out-of-date.

**Comment by dbrnz** [comment]
@alan-wu how did you get on? I've just tried a clean build under Windows (from the command prompt) and everything is just fine...

**Comment by alan-wu** [comment]
@dbrnz It works now. Clean all using Qt Creator did not clean up properly. I removed the build folder and reconfigured the project at the end. Thanks.

**Comment by agarny** [comment]
Yes, sorry for that @alan-wu. This is why I created those `clean[all][.bat]` scripts (and the other scripts) to make sure that everything works as I would expect.

**Comment by agarny** [comment]
Thanks also @dbrnz for helping. Much appreciated.

**Pull request merged**
