### PR TITLE
Get a working GUI console under Windows

### LINKED ISSUE #2779: Python: the `Python Console` window is empty under Windows
I'm looking into this...

### PR DESCRIPTION
**Pull request by dbrnz**
This resolves #2779.

There may be an edge case with Jupyter raising an exception because PythonQt's redirected stdout doesn't provide `fileno()`, although everything appears fine with my testing. (The `fileno` issue, together with up/down keys not working at the `pythonshell` command prompt, was why redirection via PythonQt was removed; Windows Python though has an inbuilt `readline` and up/down keys in fact still work).

### CODE REVIEW

**Comment by agarny** [comment]
@dbrnz, am I to understand that it's all good to be reviewed and merged in? (I will obviously make sure that I can now get the `Python Console` window to work under Windows.)

**Comment by dbrnz** [comment]
Yes, all good to merge.

**Comment by agarny** [comment]
> Yes, all good to merge.

Great, thanks! However, I tried to push some minor cleaning ups and authentication failed even though I am connected to GitHub and everything. Could it be that I cannot push to your PR for some reasons (while I could for your previous one)?

**Comment by agarny** [comment]
> Nothing has changed on this end...

Yes, my bad: I always edit `.git/config` to add a remote and... yeah, I screwed up!

**Pull request merged**
