### PR TITLE
Travis CI: tests can't be built on Linux (#1395)

### PR DESCRIPTION
**Pull request by agarny**

### CODE REVIEW

**Comment by agarny** [comment]
Ok, at this stage, I have managed to get an Ubuntu 16.04 Docker container set up. GCC/G++ and Qt, among other things, get installed. However, the problem, now, is how do we get the right commit for our OpenCOR repository. Indeed, the container obviously doesn't contain anything, so we need to `git clone` the OpenCOR repository and to do so for the master branch, we could simply mimic what Travis CI does, i.e.

```
git clone --depth=50 --branch=master https://github.com/opencor/opencor.git opencor/opencor
```

However, what happens in the case of pull requests (or even branches, if we ever wanted to support CI in branches)?! So, although it was starting to look promising, there is that somewhat big hurdle that needs to be addressed and, so far, I haven't managed to find the information that would allow us to do this (IOW, Travis CI + Docker really lacks 'proper' documentation).

**Comment by agarny** [comment]
Some information to help with my last comment can be found at https://docs.travis-ci.com/user/environment-variables/

**Comment by agarny** [comment]
At this stage, I have got things to build for a PR and it should work for a push to the `master` branch, but there is no proper way of testing it until this PR gets merged.

Now, this being all said, I must confess that having to use Docker within Travis CI is really not ideal since, as hinted above, we must clone our OpenCOR repository ourselves and, as expected, this requires distinguishing between a PR and a push to the `master` branch.

Anyway, I will get back to this when I am back in early September...

**Comment by dbrnz** [comment]
@agarny, would you like me to play with things while you are enjoying a well earned break?

**Comment by agarny** [comment]
Sorry, @dbrnz, I didn't get to see your message before I went away. Did you get to play with things in the end?

**Comment by agarny** [comment]
FWIW, we are now using Docker in a different way that doesn't require cloning our OpenCOR repository ourselves. Now, waiting for commit 7002fc4 to build and test on Ubuntu/macOS and in release/debug mode.

**Pull request merged**
